In [14]:
import numpy as np 

In [15]:
%run data_preprocessing/ionosphere_data.ipynb

In [46]:
class LogisticRegression:
    def __init__(self, lr=0.01, eps=1e-2, num_iter=10000, ):        
        # initialize hyperparameters 
        self.lr = lr
        self.eps = eps
        self.num_iter = num_iter
        self.w = []
        
    def add_intercept(self, X):
        N,D = X.shape
        intercept = np.ones((N, 1), dtype = X.dtype)
        return np.concatenate((intercept, X), axis=1)
        
    def sigmoid(self, Z):
        return 1 / (1 + np.exp(-Z))
    
    def fit(self, X, y):
        X = self.add_intercept(X)
        N,D = X.shape
        self.w = np.zeros(D)
        
        g = np.inf 
        
        while np.linalg.norm(g) > self.eps:
#         for i in range(100000):
            yh = self.sigmoid(np.dot(X, self.w))
            g = np.dot(X.T, (yh - y)) / N
            self.w = self.w - self.lr*g
                

    
    def predict(self, X):     
        X = self.add_intercept(X)
        N,D = X.shape
        yh = self.sigmoid(np.dot(X, self.w))
        predictions = (yh >= 0.5).astype(int)
        return predictions
        
        

    

In [47]:
X = ionosphere_export[:, :-1]
y = ionosphere_export[:, -1]


lr = LogisticRegression()
lr.fit(X, y)
lr.predict(np.matrix([[1,1,-0.02401,0.94140,0.06531,0.92106,-0.23255,0.77152,-0.16399,0.52798,-0.20275,0.56409,-0.00712,0.34395,-0.27457,0.52940,-0.21780,0.45107,-0.17813,0.05982,-0.35575,0.02309,-0.52879,0.03286,-0.65158,0.13290,-0.53206,0.02431,-0.62197,-0.05707,-0.59573,-0.04608,-0.65697],[1,1,-0.02401,0.94140,0.06531,0.92106,-0.23255,0.77152,-0.16399,0.52798,-0.20275,0.56409,-0.00712,0.34395,-0.27457,0.52940,-0.21780,0.45107,-0.17813,0.05982,-0.35575,0.02309,-0.52879,0.03286,-0.65158,0.13290,-0.53206,0.02431,-0.62197,-0.05707,-0.59573,-0.04608,-0.65697]]))

[-3.90876305  1.97134128  1.69623103  0.6887892   2.05534016  1.3002874
  0.56242602  1.68344798  1.23372793  0.13934878 -1.13491116 -0.44780797
 -0.47324959  1.00497047  0.80591848 -0.21114112  0.29745399  0.69524138
 -0.62839348 -0.01751338  0.22698444 -2.40109944  1.12854116  0.68270134
  0.58273099  1.2635086  -2.46871696 -0.33139439  0.62553685  0.84215945
  0.82819734 -0.42234506 -0.29033422 -1.34559573]


matrix([[1, 1]])

array([[    39,  77516,     13, ...,      1,      0,      0],
       [    50,  83311,     13, ...,      1,      0,      0],
       [    38, 215646,      9, ...,      1,      0,      0],
       ...,
       [    38, 374983,     13, ...,      1,      0,      0],
       [    44,  83891,     13, ...,      1,      0,      0],
       [    35, 182148,     13, ...,      1,      0,      0]], dtype=int64)

matrix([[ True]])