In [22]:
import numpy as np

In [32]:
%run data_preprocessing/ionosphere_data.ipynb

In [33]:
%run logistic_regression.ipynb

In [34]:
data = ionosphere_export
data.shape

(351, 34)

In [26]:
def get_new_model():
    return LogisticRegression()

In [27]:
def evaluate_acc(y,yh):
    tp = np.sum(np.logical_and(yh==1,y==1))
    tn = np.sum(np.logical_and(yh==0,y==0))
    
    acc = (tp+tn)/y.size
    return acc

In [28]:
def get_folds(k, data):
    np.random.shuffle(data)
    
    # Split into k-folds and remove empty splits if not appropriate size
    folds = np.array_split(data, k)
    folds = [x for x in folds if x.size > 0]
    
    return folds

In [35]:
def k_fold_cross_validation(k, data):
    folds = get_folds(k,data)
    fold_accuracies = []
    for i in range(k):
        model = get_new_model()
        
        # Get test row, and training set
        test = folds[i]
        train = np.delete(folds, i, 0)
        
        train = np.concatenate(train,axis=0)
        train = np.array(train)
        print(train)
        
        train_X = train[:, :-1]
        train_Y = train[:, -1]
        
        # Fit and predict
        model.fit(train_X, train_Y)
        test_X = test[:, :-1]
        test_Y = test[:, -1]
        model_results = model.predict(test_X)
        
        fold_accuracies.append(evaluate_acc(model_results,test_Y))
    return np.average(fold_accuracies)

In [36]:
k_fold_cross_validation(2,data)

[[ 30000      1      2 ...   1000   2759      0]
 [ 60000      1      2 ...   2000   1500      0]
 [140000      2      1 ...   1242   3061      0]
 ...
 [200000      2      1 ...      0      0      0]
 [320000      1      1 ...   7500     30      0]
 [ 90000      2      2 ...      0   1664      0]]


KeyboardInterrupt: 

0.8687619047619047