In [17]:
import pandas as pd 
import numpy as np
pd.set_option('display.max_columns', None)

thoracic_data = pd.read_csv('../data/thoracic_surgery.csv')
thoracic_data


dgn_code_b  forced_vital_capacity_g  \
0         DGN2                     2.88   
1         DGN3                     3.40   
2         DGN3                     2.76   
3         DGN3                     3.68   
4         DGN3                     2.44   
..         ...                      ...   
465       DGN2                     3.88   
466       DGN3                     3.76   
467       DGN3                     3.04   
468       DGN3                     1.96   
469       DGN3                     4.72   

     volume_exhaled_after_fs_forced_expiration_g performance_status_b  \
0                                           2.16                 PRZ1   
1                                           1.88                 PRZ0   
2                                           2.08                 PRZ1   
3                                           3.04                 PRZ0   
4                                           0.96                 PRZ2   
..                                           ...                  ...   
465                                         2.12                 PRZ1   
466                                         3.12                 PRZ0   
467                                         2.08                 PRZ1   
468                                         1.68                 PRZ1   
469                                         3.56                 PRZ0   

    pain_before_b haemoptysis_before_b dyspnoea_before_b cough_before_b  \
0               F                    F                 F              T   
1               F                    F                 F              F   
2               F                    F                 F              T   
3               F                    F                 F              F   
4               F                    T                 F              T   
..            ...                  ...               ...            ...   
465             F                    F                 F              T   
466             F                    F                 F              F   
467             F                    F                 F              T   
468             F                    F                 F              T   
469             F                    F                 F              F   

    weakness_before_b size_of_original_tumour_g type_2_diabetes_b  \
0                   T                      OC14                 F   
1                   F                      OC12                 F   
2                   F                      OC11                 F   
3                   F                      OC11                 F   
4                   T                      OC11                 F   
..                ...                       ...               ...   
465                 F                      OC13                 F   
466                 F                      OC11                 F   
467                 F                      OC13                 F   
468                 T                      OC12                 F   
469                 F                      OC12                 F   

    mi_up_to_6_months_g pad_b smoking_b asthma_b  age_at_surgery_g  \
0                     F     F         T        F                60   
1                     F     F         T        F                51   
2                     F     F         T        F                59   
3                     F     F         F        F                54   
4                     F     F         T        F                73   
..                  ...   ...       ...      ...               ...   
465                   F     F         T        F                63   
466                   F     F         T        F                61   
467                   F     F         F        F                52   
468                   F     F         T        F                79   
469                   F     F         T        F                51   

    survival_after_one_year_b  
0      

In [20]:
thoracic_data.loc[thoracic_data['dgn_code_b'] == 'DGN1', 'dgn_code_b'] = 1
thoracic_data.loc[thoracic_data['dgn_code_b'] == 'DGN2', 'dgn_code_b'] = 2
thoracic_data.loc[thoracic_data['dgn_code_b'] == 'DGN3', 'dgn_code_b'] = 3
thoracic_data.loc[thoracic_data['dgn_code_b'] == 'DGN4', 'dgn_code_b'] = 4
thoracic_data.loc[thoracic_data['dgn_code_b'] == 'DGN5', 'dgn_code_b'] = 5
thoracic_data.loc[thoracic_data['dgn_code_b'] == 'DGN6', 'dgn_code_b'] = 6
thoracic_data.loc[thoracic_data['dgn_code_b'] == 'DGN7', 'dgn_code_b'] = 7
thoracic_data.loc[thoracic_data['dgn_code_b'] == 'DGN8', 'dgn_code_b'] = 8

thoracic_data.dgn_code_b.unique()

C:\Users\heath\Anaconda3\lib\site-packages\pandas\core\ops\__init__.py:1115: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  result = method(y)


array([2, 3, 4, 8, 5, 6, 1], dtype=int64)

In [21]:
thoracic_data.loc[thoracic_data['performance_status_b'] == 'PRZ0', 'performance_status_b'] = 0
thoracic_data.loc[thoracic_data['performance_status_b'] == 'PRZ1', 'performance_status_b'] = 1
thoracic_data.loc[thoracic_data['performance_status_b'] == 'PRZ2', 'performance_status_b'] = 2


thoracic_data.performance_status_b.unique()

array([1, 0, 2], dtype=int64)

In [22]:
thoracic_data.loc[thoracic_data['size_of_original_tumour_g'] == 'OC11', 'size_of_original_tumour_g'] = 11
thoracic_data.loc[thoracic_data['size_of_original_tumour_g'] == 'OC12', 'size_of_original_tumour_g'] = 12
thoracic_data.loc[thoracic_data['size_of_original_tumour_g'] == 'OC13', 'size_of_original_tumour_g'] = 13
thoracic_data.loc[thoracic_data['size_of_original_tumour_g'] == 'OC14', 'size_of_original_tumour_g'] = 14


thoracic_data.size_of_original_tumour_g.unique()

array([14, 12, 11, 13], dtype=int64)

In [12]:
def true_false_converter(thoracic_data, column):
    thoracic_data.loc[thoracic_data[column] == 'T', column] = 1
    thoracic_data.loc[thoracic_data[column] == 'F', column] = 0

In [24]:
true_false_converter(thoracic_data,"pain_before_b")
true_false_converter(thoracic_data,"haemoptysis_before_b")
true_false_converter(thoracic_data,"dyspnoea_before_b")
true_false_converter(thoracic_data,"cough_before_b")
true_false_converter(thoracic_data,"weakness_before_b")
true_false_converter(thoracic_data,"type_2_diabetes_b")
true_false_converter(thoracic_data,"mi_up_to_6_months_g")
true_false_converter(thoracic_data,"pad_b")
true_false_converter(thoracic_data,"smoking_b")
true_false_converter(thoracic_data,"asthma_b")
true_false_converter(thoracic_data,"survival_after_one_year_b")

In [25]:
thoracic_data

dgn_code_b  forced_vital_capacity_g  \
0             2                     2.88   
1             3                     3.40   
2             3                     2.76   
3             3                     3.68   
4             3                     2.44   
..          ...                      ...   
465           2                     3.88   
466           3                     3.76   
467           3                     3.04   
468           3                     1.96   
469           3                     4.72   

     volume_exhaled_after_fs_forced_expiration_g  performance_status_b  \
0                                           2.16                     1   
1                                           1.88                     0   
2                                           2.08                     1   
3                                           3.04                     0   
4                                           0.96                     2   
..                                           ...                   ...   
465                                         2.12                     1   
466                                         3.12                     0   
467                                         2.08                     1   
468                                         1.68                     1   
469                                         3.56                     0   

     pain_before_b  haemoptysis_before_b  dyspnoea_before_b  cough_before_b  \
0                0                     0                  0               1   
1                0                     0                  0               0   
2                0                     0                  0               1   
3                0                     0                  0               0   
4                0                     1                  0               1   
..             ...                   ...                ...             ...   
465              0                     0                  0               1   
466              0                     0                  0               0   
467              0                     0                  0               1   
468              0                     0                  0               1   
469              0                     0                  0               0   

     weakness_before_b  size_of_original_tumour_g  type_2_diabetes_b  \
0                    1                         14                  0   
1                    0                         12                  0   
2                    0                         11                  0   
3                    0                         11                  0   
4                    1                         11                  0   
..                 ...                        ...                ...   
465                  0                         13                  0   
466                  0                         11                  0   
467                  0                         13                  0   
468                  1                         12                  0   
469                  0                         12                  0   

     mi_up_to_6_months_g  pad_b  smoking_b  asthma_b  age_at_surgery_g  \
0                      0      0          1         0                60   
1                      0      0          1         0                51   
2                      0      0          1         0                59   
3                      0      0          0         0                54   
4                      0      0          1         0                73   
..                   ...    ...        ...       ...               ...   
465                    0      0          1         0                63   
466                    0      0          1         0                61   
467                    0      0          0         0                52   
468                    0      0  

In [26]:
thoracic_data_export = np.array(thoracic_data)

In [27]:
thoracic_data_export

%store thoracic_data_export 

Stored 'thoracic_data_export' (ndarray)
