In [10]:
import pandas as pd 
import numpy as np
pd.set_option('display.max_columns', None)

thoracic_data = pd.read_csv('../data/thoracic_surgery.csv')
thoracic_data


dgn_code_b  forced_vital_capacity_g  \
0         DGN2                     2.88   
1         DGN3                     3.40   
2         DGN3                     2.76   
3         DGN3                     3.68   
4         DGN3                     2.44   
5         DGN3                     2.48   
6         DGN3                     4.36   
7         DGN2                     3.19   
8         DGN3                     3.16   
9         DGN3                     2.32   
10        DGN3                     2.56   
11        DGN3                     4.28   
12        DGN3                     3.00   
13        DGN2                     3.98   
14        DGN3                     1.96   
15        DGN3                     4.68   
16        DGN2                     2.21   
17        DGN2                     2.96   
18        DGN3                     2.60   
19        DGN3                     2.88   
20        DGN3                     4.48   
21        DGN4                     3.32   
22        DGN3                     2.36   
23        DGN3                     3.68   
24        DGN8                     4.32   
25        DGN5                     4.56   
26        DGN3                     3.24   
27        DGN3                     3.40   
28        DGN3                     3.16   
29        DGN6                     3.96   
..         ...                      ...   
440       DGN3                     3.00   
441       DGN2                     4.44   
442       DGN2                     4.08   
443       DGN3                     4.12   
444       DGN3                     2.56   
445       DGN3                     2.72   
446       DGN8                     5.20   
447       DGN2                     4.40   
448       DGN3                     2.96   
449       DGN3                     2.84   
450       DGN3                     2.28   
451       DGN4                     3.04   
452       DGN3                     2.80   
453       DGN3                     2.84   
454       DGN3                     3.24   
455       DGN4                     2.92   
456       DGN3                     2.40   
457       DGN3                     4.56   
458       DGN3                     3.60   
459       DGN3                     4.28   
460       DGN4                     4.65   
461       DGN3                     1.84   
462       DGN3                     2.12   
463       DGN4                     3.44   
464       DGN3                     3.08   
465       DGN2                     3.88   
466       DGN3                     3.76   
467       DGN3                     3.04   
468       DGN3                     1.96   
469       DGN3                     4.72   

     volume_exhaled_after_fs_forced_expiration_g performance_status_b  \
0                                           2.16                 PRZ1   
1                                           1.88                 PRZ0   
2                                           2.08                 PRZ1   
3                                           3.04                 PRZ0   
4                                           0.96                 PRZ2   
5                                           1.88                 PRZ1   
6                                           3.28                 PRZ1   
7                                           2.50                 PRZ1   
8                                           2.64                 PRZ2   
9                                           2.16                 PRZ1   
10                                          2.32                 PRZ0   
11                                          4.44                 PRZ1   
12                                          2.36                 PRZ1   
13                                          3.06                 PRZ2   
14                                          1.40                 PRZ1   
15                                          4.16                 PRZ1   
16                                          1.88                 PRZ0   
17                     

In [11]:
thoracic_data.loc[thoracic_data['dgn_code_b'] == 'DGN1', 'dgn_code_b'] = 1
thoracic_data.loc[thoracic_data['dgn_code_b'] == 'DGN2', 'dgn_code_b'] = 2
thoracic_data.loc[thoracic_data['dgn_code_b'] == 'DGN3', 'dgn_code_b'] = 3
thoracic_data.loc[thoracic_data['dgn_code_b'] == 'DGN4', 'dgn_code_b'] = 4
thoracic_data.loc[thoracic_data['dgn_code_b'] == 'DGN5', 'dgn_code_b'] = 5
thoracic_data.loc[thoracic_data['dgn_code_b'] == 'DGN6', 'dgn_code_b'] = 6
thoracic_data.loc[thoracic_data['dgn_code_b'] == 'DGN7', 'dgn_code_b'] = 7
thoracic_data.loc[thoracic_data['dgn_code_b'] == 'DGN8', 'dgn_code_b'] = 8

thoracic_data.dgn_code_b.unique()

array([2, 3, 4, 8, 5, 6, 1])

In [12]:
thoracic_data.loc[thoracic_data['performance_status_b'] == 'PRZ0', 'performance_status_b'] = 0
thoracic_data.loc[thoracic_data['performance_status_b'] == 'PRZ1', 'performance_status_b'] = 1
thoracic_data.loc[thoracic_data['performance_status_b'] == 'PRZ2', 'performance_status_b'] = 2


thoracic_data.performance_status_b.unique()

array([1, 0, 2])

In [13]:
thoracic_data.loc[thoracic_data['size_of_original_tumour_g'] == 'OC11', 'size_of_original_tumour_g'] = 11
thoracic_data.loc[thoracic_data['size_of_original_tumour_g'] == 'OC12', 'size_of_original_tumour_g'] = 12
thoracic_data.loc[thoracic_data['size_of_original_tumour_g'] == 'OC13', 'size_of_original_tumour_g'] = 13
thoracic_data.loc[thoracic_data['size_of_original_tumour_g'] == 'OC14', 'size_of_original_tumour_g'] = 14


thoracic_data.size_of_original_tumour_g.unique()

array([14, 12, 11, 13])

In [14]:
def true_false_converter(thoracic_data, column):
    thoracic_data.loc[thoracic_data[column] == 'T', column] = 1
    thoracic_data.loc[thoracic_data[column] == 'F', column] = 0

In [15]:
true_false_converter(thoracic_data,"pain_before_b")
true_false_converter(thoracic_data,"haemoptysis_before_b")
true_false_converter(thoracic_data,"dyspnoea_before_b")
true_false_converter(thoracic_data,"cough_before_b")
true_false_converter(thoracic_data,"weakness_before_b")
true_false_converter(thoracic_data,"type_2_diabetes_b")
true_false_converter(thoracic_data,"mi_up_to_6_months_b")
true_false_converter(thoracic_data,"pad_b")
true_false_converter(thoracic_data,"smoking_b")
true_false_converter(thoracic_data,"asthma_b")
true_false_converter(thoracic_data,"survival_after_one_year_b")

In [16]:
thoracic_data

dgn_code_b  forced_vital_capacity_g  \
0             2                     2.88   
1             3                     3.40   
2             3                     2.76   
3             3                     3.68   
4             3                     2.44   
5             3                     2.48   
6             3                     4.36   
7             2                     3.19   
8             3                     3.16   
9             3                     2.32   
10            3                     2.56   
11            3                     4.28   
12            3                     3.00   
13            2                     3.98   
14            3                     1.96   
15            3                     4.68   
16            2                     2.21   
17            2                     2.96   
18            3                     2.60   
19            3                     2.88   
20            3                     4.48   
21            4                     3.32   
22            3                     2.36   
23            3                     3.68   
24            8                     4.32   
25            5                     4.56   
26            3                     3.24   
27            3                     3.40   
28            3                     3.16   
29            6                     3.96   
..          ...                      ...   
440           3                     3.00   
441           2                     4.44   
442           2                     4.08   
443           3                     4.12   
444           3                     2.56   
445           3                     2.72   
446           8                     5.20   
447           2                     4.40   
448           3                     2.96   
449           3                     2.84   
450           3                     2.28   
451           4                     3.04   
452           3                     2.80   
453           3                     2.84   
454           3                     3.24   
455           4                     2.92   
456           3                     2.40   
457           3                     4.56   
458           3                     3.60   
459           3                     4.28   
460           4                     4.65   
461           3                     1.84   
462           3                     2.12   
463           4                     3.44   
464           3                     3.08   
465           2                     3.88   
466           3                     3.76   
467           3                     3.04   
468           3                     1.96   
469           3                     4.72   

     volume_exhaled_after_fs_forced_expiration_g  performance_status_b  \
0                                           2.16                     1   
1                                           1.88                     0   
2                                           2.08                     1   
3                                           3.04                     0   
4                                           0.96                     2   
5                                           1.88                     1   
6                                           3.28                     1   
7                                           2.50                     1   
8                                           2.64                     2   
9                                           2.16                     1   
10                                          2.32                     0   
11                                          4.44                     1   
12                                          2.36                     1   
13                                          3.06                     2   
14                                          1.40                     1   
15                                          4.16                     1   
16                

In [17]:
thoracic_export = np.array(thoracic_data)
thoracic_headers = np.array(thoracic_data.columns)


In [18]:
%store thoracic_export 
%store thoracic_headers

Stored 'thoracic_export' (ndarray)
Stored 'thoracic_headers' (ndarray)
